// <auto-generated />
using System;
using Console_Runner.Logging;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mircoservice_Food.Migrations
{
    [DbContext(typeof(ContextLoggingDB))]
    [Migration("20220426003412_LoggingDB")]
    partial class LoggingDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Console_Runner.Logging.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("LogLevel")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserIdentifierUserHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LogId");

                    b.HasIndex("UserIdentifierUserHash");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Console_Runner.Logging.UserIdentifier", b =>
                {
                    b.Property<string>("UserHash")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserHash");

                    b.ToTable("UIDs");
                });

            modelBuilder.Entity("Console_Runner.Logging.Log", b =>
                {
                    b.HasOne("Console_Runner.Logging.UserIdentifier", "UserIdentifier")
                        .WithMany("Logs")
                        .HasForeignKey("UserIdentifierUserHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserIdentifier");
                });

            modelBuilder.Entity("Console_Runner.Logging.UserIdentifier", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
